'use strict';

var PLAYER_SPEED = 65;
var PLAYER_LUMENS = 65;
var PLAYER_COLLIDE_RADIUS = 2;

var FLARE_MAX_ROTATE_SPEED = 10;

var FLAME_DELAY = 150;
var FLAME_SPREAD = Math.PI/8;
var FLAME_SPEED = 350;
var FLAME_LUMENS = 30;
var FLAME_TTL = 750;

var FIREBALL_DELAY = 750;
var FIREBALL_SPEED = 300;
var FIREBALL_LUMENS = 10;
var FIREBALL_FLARES = 15;
var FIREBALL_FLARES_MAX_SPEED = 300;
var FIREBALL_FLARES_LUMENS = 30;
var FIREBALL_FLARES_MAX_TTL = 1000;

var LAMPSTAND_LUMENS = 550;
var LAMPSTAND_LUMENS_SPEED = 200;
var LAMPSTAND_FIREBALL_DELAY = 500;
var LAMPSTAND_MAX_DISTANCE = 3500;
var LAMPSTAND_MIN_DISTANCE = 1000;

var BLOB_MAX_SIZE = 50;
var BLOB_MIN_SIZE = 15;
var BLOB_MAX_SPEED = 100;
var BLOB_MIN_SPEED = 20;
var BLOB_MAX_ROTATE_SPEED = 2;
var BLOB_SPAWN_MAX_DELAY = 3000;
var BLOB_SPAWN_MIN_DELAY = 500;
var BLOB_SPAWN_MAX_DISTANCE = 300;
var BLOB_SPAWN_MIN_DISTANCE = 100;
var BLOB_DO_SPAWN = true;

function setPlayerLevel(level){
	switch(level){
		case 0:
			PLAYER_LUMENS = 45;

			FLAME_DELAY = 500;
			FLAME_SPREAD = Math.PI/32;
			FLAME_SPEED = 250;
			FLAME_LUMENS = 20;
			FLAME_TTL = 500;

			FIREBALL_DELAY = 1500;
			FIREBALL_SPEED = 150;
			FIREBALL_LUMENS = 10;
			FIREBALL_FLARES = 5;
			FIREBALL_FLARES_MAX_SPEED = 200;
			FIREBALL_FLARES_LUMENS = 30;
			FIREBALL_FLARES_MAX_TTL = 500;

			BLOB_DO_SPAWN = false;

			break;

		case 1:
			PLAYER_LUMENS = 60;

			FLAME_DELAY = 350;
			FLAME_SPREAD = Math.PI/16;
			FLAME_SPEED = 275;
			FLAME_LUMENS = 20;
			FLAME_TTL = 500;

			FIREBALL_DELAY = 1500;
			FIREBALL_SPEED = 150;
			FIREBALL_LUMENS = 10;
			FIREBALL_FLARES = 7;
			FIREBALL_FLARES_MAX_SPEED = 225;
			FIREBALL_FLARES_LUMENS = 30;
			FIREBALL_FLARES_MAX_TTL = 600;

			BLOB_SPAWN_MAX_DELAY = 5000;
			BLOB_SPAWN_MIN_DELAY = 1000;
			BLOB_SPAWN_MAX_DISTANCE = 500;
			BLOB_SPAWN_MIN_DISTANCE = 250;
			BLOB_DO_SPAWN = true;

			break;

		case 2:
			PLAYER_LUMENS = 75;

			FLAME_DELAY = 300;
			FLAME_SPREAD = Math.PI/16;
			FLAME_SPEED = 300;
			FLAME_LUMENS = 30;
			FLAME_TTL = 500;

			FIREBALL_DELAY = 1250;
			FIREBALL_SPEED = 200;
			FIREBALL_LUMENS = 10;
			FIREBALL_FLARES = 10;
			FIREBALL_FLARES_MAX_SPEED = 250;
			FIREBALL_FLARES_LUMENS = 30;
			FIREBALL_FLARES_MAX_TTL = 650;

			BLOB_SPAWN_MAX_DELAY = 3500;
			BLOB_SPAWN_MIN_DELAY = 750;
			BLOB_SPAWN_MAX_DISTANCE = 500;
			BLOB_SPAWN_MIN_DISTANCE = 250;
			BLOB_DO_SPAWN = true;

			break;

		case 3:
			PLAYER_LUMENS = 90;

			FLAME_DELAY = 225;
			FLAME_SPREAD = Math.PI/16;
			FLAME_SPEED = 300;
			FLAME_LUMENS = 30;
			FLAME_TTL = 600;

			FIREBALL_DELAY = 1000;
			FIREBALL_SPEED = 250;
			FIREBALL_LUMENS = 10;
			FIREBALL_FLARES = 12;
			FIREBALL_FLARES_MAX_SPEED = 275;
			FIREBALL_FLARES_LUMENS = 30;
			FIREBALL_FLARES_MAX_TTL = 750;

			BLOB_SPAWN_MAX_DELAY = 3000;
			BLOB_SPAWN_MIN_DELAY = 500;
			BLOB_SPAWN_MAX_DISTANCE = 500;
			BLOB_SPAWN_MIN_DISTANCE = 200;
			BLOB_DO_SPAWN = true;

			break;

		case 4:
			PLAYER_LUMENS = 105;

			FLAME_DELAY = 150;
			FLAME_SPREAD = Math.PI/8;
			FLAME_SPEED = 300;
			FLAME_LUMENS = 30;
			FLAME_TTL = 600;

			FIREBALL_DELAY = 1000;
			FIREBALL_SPEED = 300;
			FIREBALL_LUMENS = 10;
			FIREBALL_FLARES = 15;
			FIREBALL_FLARES_MAX_SPEED = 300;
			FIREBALL_FLARES_LUMENS = 30;
			FIREBALL_FLARES_MAX_TTL = 1000;

			BLOB_SPAWN_MAX_DELAY = 2000;
			BLOB_SPAWN_MIN_DELAY = 500;
			BLOB_SPAWN_MAX_DISTANCE = 500;
			BLOB_SPAWN_MIN_DISTANCE = 200;
			BLOB_DO_SPAWN = true;

			break;

		case 5:
			PLAYER_LUMENS = 120;

			FLAME_DELAY = 100;
			FLAME_SPREAD = Math.PI/4;
			FLAME_SPEED = 300;
			FLAME_LUMENS = 30;
			FLAME_TTL = 600;

			FIREBALL_DELAY = 1000;
			FIREBALL_SPEED = 300;
			FIREBALL_LUMENS = 10;
			FIREBALL_FLARES = 20;
			FIREBALL_FLARES_MAX_SPEED = 350;
			FIREBALL_FLARES_LUMENS = 30;
			FIREBALL_FLARES_MAX_TTL = 1000;

			BLOB_SPAWN_MAX_DELAY = 1500;
			BLOB_SPAWN_MIN_DELAY = 250;
			BLOB_SPAWN_MAX_DISTANCE = 500;
			BLOB_SPAWN_MIN_DISTANCE = 200;
			BLOB_DO_SPAWN = true;

			break;

		case 6:
			PLAYER_LUMENS = 135;

			FLAME_DELAY = 50;
			FLAME_SPREAD = Math.PI/4;
			FLAME_SPEED = 300;
			FLAME_LUMENS = 50;
			FLAME_TTL = 600;

			FIREBALL_DELAY = 1000;
			FIREBALL_SPEED = 500;
			FIREBALL_LUMENS = 20;
			FIREBALL_FLARES = 30;
			FIREBALL_FLARES_MAX_SPEED = 500;
			FIREBALL_FLARES_LUMENS = 50;
			FIREBALL_FLARES_MAX_TTL = 1500;

			BLOB_SPAWN_MAX_DELAY = 500;
			BLOB_SPAWN_MIN_DELAY = 100;
			BLOB_SPAWN_MAX_DISTANCE = 500;
			BLOB_SPAWN_MIN_DISTANCE = 200;
			BLOB_DO_SPAWN = true;

			break;
	}
}
