'use strict';

var PLAYER_SPEED = 65;
var PLAYER_LUMENS = 65;

var FLARE_MAX_ROTATE_SPEED = 10;

var FLAME_DELAY = 150;
var FLAME_SPREAD = Math.PI/8;
var FLAME_SPEED = 350;
var FLAME_LUMENS = 30;
var FLAME_TTL = 750;

var FIREBALL_DELAY = 750;
var FIREBALL_SPEED = 300;
var FIREBALL_LUMENS = 10;
var FIREBALL_FLARES = 15;
var FIREBALL_FLARES_MAX_SPEED = 300;
var FIREBALL_FLARES_LUMENS = 30;
var FIREBALL_FLARES_MAX_TTL = 1000;

var LAMPSTAND_LUMENS = 550;
var LAMPSTAND_LUMENS_SPEED = 200;
var LAMPSTAND_FIREBALL_DELAY = 500;
