'use strict';

var PLAYER_SPEED = 65;
var PLAYER_LUMENS = 65;

var FLARE_MAX_ROTATE_SPEED = 10;

var FLAME_DELAY = 150;
var FLAME_SPREAD = Math.PI/8;
var FLAME_SPEED = 350;
var FLAME_LUMENS = 30;
var FLAME_TTL = 750;
